name: Docker

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Pterodactyl image
        id: docker_build_ptero
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: csmm/csmm-pterodactyl:latest
          context: Pterodactyl
          file: Pterodactyl/Dockerfile
      - name: Build and push Traefik config image
        id: docker_build_traefik
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: csmm/csmm-traefik:latest
          context: traefik-http
          file: traefik-http/Dockerfile
